### ISSUE TITLE
阿里云 kubernetes 中regexp format 解析失败

### ISSUE THREAD

**Issue by zhangyuming** [AliyunContainerService/log-pilot#116]
你好, 我在阿里云容器服务中部署log-pilot 日志格式化策略选用的是 regexp  日志解析格式没有生效请帮忙确认下问题:
deployment 配置如下
```
        env:
        - name: aliyun_logs_webapp-dev
          value: "stdout"
        - name: aliyun_logs_webapp-dev.format
          value: "regexp"
        - name: aliyun_logs_webapp-dev.format.pattern
          value: "^\\[(?<time>\\d{1,4}-\\d{1,2}-\\d{1,2} \\d{1,2}:\\d{1,2}:\\d{1,2},\\d{1,4})\\] \\[(?<thread>.*)\\] \\[(?<level>[^\\s]+)\\] (?<class>[^\\s]+) (?<message>.*)$"

```
应用日志
```
[2018-05-23 17:17:13,606] [http-bio-8080-exec-2] [INFO] hanhua.qa.web.action.ElementAction.findPagedElementsAction:51 ########## length is : 50
[2018-05-23 17:17:13,606] [http-bio-8080-exec-2] [INFO] hanhua.qa.web.action.ElementAction.findPagedElementsAction:52 ############ source is : dataSourceP2P
[2018-05-23 17:17:13,606] [http-bio-8080-exec-2] [INFO] hanhua.qa.web.action.ElementAction.findPagedElementsAction:53 ########## search is : {"value":"","regex":false}
[2018-05-23 17:17:13,607] [http-bio-8080-exec-2] [INFO] hanhua.qa.web.action.BaseAction.setTargetDataSource:68 Switch Dynamic DataSource to : dataSourceP2P
```
log-pilot 日志如下
```
time="2018-05-23T09:15:41Z" level=info msg="begin to watch log config: 670000c4ba6cb4791d1f16ffacd7773a87eee47f8fc05e1db74a571c26321f4d.yml" 
time="2018-05-23T09:16:00Z" level=debug msg="Process container start event: 02d02ac312116b0b65c5e384ab3fd422a1978a84ab9501488ada4a5d9e09153a" 
time="2018-05-23T09:16:00Z" level=debug msg="02d02ac312116b0b65c5e384ab3fd422a1978a84ab9501488ada4a5d9e09153a has not log config, skip" 
time="2018-05-23T09:16:00Z" level=debug msg="Process container start event: 73bb79295c1a00162ef879f202fca30992e8db7c7e4b127568b33aa532934f6e" 
time="2018-05-23T09:16:00Z" level=info msg="logs: 73bb79295c1a00162ef879f202fca30992e8db7c7e4b127568b33aa532934f6e = &{webapp-dev /host/var/lib/docker/containers/73bb79295c1a00162ef879f202fca30992e8db7c7e4b127568b33aa532934f6e  /^\[(?<time>\d{1,4}-\d{1,2}-\d{1,2} \d{1,2}:\d{1,2}:\d{1,2},\d{1,4})\] \[(?<thread>.*)\] \[(?<level>[^\s]+)\] (?<class>[^\s]+) (?<message>.*)$/ map[time_format:%Y-%m-%dT%H:%M:%S.%NZ] 73bb79295c1a00162ef879f202fca30992e8db7c7e4b127568b33aa532934f6e-json.log* map[index:webapp-dev topic:webapp-dev]  false true}" 
time="2018-05-23T09:16:00Z" level=info msg="Reload filebeat" 
time="2018-05-23T09:16:00Z" level=info msg="Start reloading" 
time="2018-05-23T09:16:00Z" level=debug msg="not need to reload filebeat" 
time="2018-05-23T09:16:15Z" level=info msg="try to remove log config 670000c4ba6cb4791d1f16ffacd7773a87eee47f8fc05e1db74a571c26321f4d.yml" 
time="2018-05-23T09:16:35Z" level=debug msg="Process container destory event: 83f0bbc6b5d3114894ad366a58e1c24f89496a530627d474498638457055a06c" 
time="2018-05-23T09:16:35Z" level=info msg="begin to watch log config: 83f0bbc6b5d3114894ad366a58e1c24f89496a530627d474498638457055a06c.yml" 
time="2018-05-23T09:17:15Z" level=info msg="log config 83f0bbc6b5d3114894ad366a58e1c24f89496a530627d474498638457055a06c.yml has been removed and ignore" 

```
最后解析出来的message 仍然是原来的日志, 没有解析出来level和thread
```
[2018-05-23 17:17:24,980] [http-bio-8080-exec-5] [INFO] hanhua.qa.web.action.BaseAction.setTargetDataSource:68 Switch Dynamic DataSource to : dataSourceP2P
```

log-pilot 里面并没有解析失败的日志
以上是问题描述，初次之外我想了解如下的问题
- 这个日志格式解析是在filebeat里面还是在elasticsearch里面用ingest？  
- 有没有匹配多行分割的功能，能否把java堆栈匹配成一条日志呢
