### ISSUE TITLE
log-pilot如何处理tomcat多行日志

### ISSUE THREAD

**Issue by amoyx** [AliyunContainerService/log-pilot#121]
在kibana上显示的信息，发现catalina.out本来是一行的，变成多行显示，很不方便，要如何处理？

**Comment by amoyx** [comment]
labels:      
    - aliyun.logs.tomcat=tdout
    - aliyun.logs.tomcat.format=regexp
    - aliyun.logs.tomcat.format.pattern="^[[:space:]]"
如果用正则匹配，这样写可不可以,我这样写了，不生效
@xuil

**Comment by chenqz1987** [comment]
@amoyx 采集日志时默认就是按行来采集的，您使用的是filebeat plugin吗？

**Comment by amoyx** [comment]
嗯，是 filebeat ，要如何把 catalina.out的多行日志合并成一行  @chenqz1987

**Comment by crystonesc** [comment]
希望有种办法能把filebeat的multiline给配置进filebeat才行

**Comment by chenqz1987** [comment]
目前还不支持，后续我们考虑加入进去

**Comment by amoyx** [comment]
@chenqz1987  你好，要怎样才可以把 tomcat多行日志合并成一行？

**Comment by chenquanzhao** [comment]
目前还不支持哈

**Comment by qq676596084** [comment]
把filebeat.tpl 配置 新增 multiline 即可
重新生成一个镜像 tomcat多行日志即可合并
vim filebeat.tpl
  {{range .configList}}
  ...
  multiline.pattern: '^[[:space:]]+(at|\.{3})\b|^Caused by:'
  multiline.negate: false
  multiline.match: after
  multiline.max_lines: 10000
  scan_frequency: 10s

**Comment by amoyx** [comment]
@qq676596084   是要把log-poilt镜像里面的  filebeat.tpl文件添加你上面的内容，对吧？

**Comment by qq676596084** [comment]
是的

**Comment by amoyx** [comment]
@qq676596084  你好大神，是改成图中的样子不？
![image](https://user-images.githubusercontent.com/19795002/45066020-d6f6be80-b0ee-11e8-8d75-a041ef901d7f.png)

**Comment by amoyx** [comment]
@qq676596084  你好，按照上图的操作还是不能处理多行日志， 多行日志依然一行一行显示， 麻烦把你的  filebeat.tpl 贴出来看看，多谢！

**Comment by amoyx** [comment]
@qq676596084  我的改完后，查询时如图所示：
![image](https://user-images.githubusercontent.com/19795002/45074150-ee48a280-b114-11e8-87c0-661fcfdba1cc.png)

**Comment by amoyx** [comment]
没有你的好看， 全是json

**Comment by JDalready** [comment]
@amoyx   可以问下你什么版本的吗？ 为什么我改了不生效   只需要重启Tomcat镜像吧 ？

**Comment by Linuxbody** [comment]
@qq676596084 
这添加完那些 还是没生效，log-pilot:0.9.7-filebeat 镜像
启动的时候多了一行
![image](https://user-images.githubusercontent.com/9931457/63762673-ce962580-c8f5-11e9-89a7-ef26304a0501.png)

但是下面看日志也收取到了，但是es里面完全没数据，不添加那几行就正常写入es
![image](https://user-images.githubusercontent.com/9931457/63762809-0d2be000-c8f6-11e9-8d18-6872fc01d62b.png)

**Comment by Linuxbody** [comment]
@qq676596084 
@JDalready 
这添加完那些 还是没生效，log-pilot:0.9.7-filebeat 镜像
启动的时候多了一行
![image](https://user-images.githubusercontent.com/9931457/63762673-ce962580-c8f5-11e9-89a7-ef26304a0501.png)

但是下面看日志也收取到了，但是es里面完全没数据，不添加那几行就正常写入es
![image](https://user-images.githubusercontent.com/9931457/63762809-0d2be000-c8f6-11e9-8d18-6872fc01d62b.png)

**Comment by dessler** [comment]
> @amoyx
> ![蒂姆20180905113722](https://user-images.githubusercontent.com/18547632/45069670-3f01d080-b100-11e8-8aba-df8eefb35c34.png)
> 
> 效果：
> 
> ![蒂姆20180905114003](https://user-images.githubusercontent.com/18547632/45069714-73758c80-b100-11e8-9683-eeecf886143a.png)

我这里显示可以合并多行，但是好像at就只有几行 和真在的比at的行数要小很多

**Comment by chenquanzhao** [comment]
@qq676596084 欢迎提PR

**Comment by nieqibest** [comment]
@dessler 
不是少了，你需要展开那条日志才能看到所有的at
![image](https://user-images.githubusercontent.com/15606003/69523412-ca35e300-0f9e-11ea-9e8a-1b457f1ac744.png)

**Comment by currycan** [comment]
你们用的什么版本？0.9.7吗？
我刚配置了一下：
```text
{{range .configList}}
- type: log
  enabled: true
  paths:
      - {{ .HostDir }}/{{ .File }}
  multiline.pattern: '^[[:space:]]+(at|\.{3})[[:space:]]+\b|^Caused by:'
  multiline.negate: false
  multiline.match: after
  scan_frequency: 10s
  fields_under_root: true
  {{if .Stdout}}
  docker-json: true
  {{end}}
  {{if eq .Format "json"}}
  json.keys_under_root: true
  {{end}}
  fields:
      {{range $key, $value := .CustomFields}}
      {{ $key }}: {{ $value }}
      {{end}}
      {{range $key, $value := .Tags}}
      {{ $key }}: {{ $value }}
      {{end}}
      {{range $key, $value := $.container}}
      {{ $key }}: {{ $value }}
      {{end}}
  {{range $key, $value := .CustomConfigs}}
  {{ $key }}: {{ $value }}
  {{end}}
  tail_files: false
  close_inactive: 2h
  close_eof: false
  close_removed: true
  clean_removed: true
  close_renamed: false

{{end}}

```
错误日志如下：
![error-log](https://tva1.sinaimg.cn/large/007S8ZIlgy1gff4z7yk46j328i084wr6.jpg)

**Comment by omegazeng** [comment]
> 你们用的什么版本？0.9.7吗？
> 我刚配置了一下：
> 
> ```
> {{range .configList}}
> - type: log
>   enabled: true
>   paths:
>       - {{ .HostDir }}/{{ .File }}
>   multiline.pattern: '^[[:space:]]+(at|\.{3})[[:space:]]+\b|^Caused by:'
>   multiline.negate: false
>   multiline.match: after
>   scan_frequency: 10s
>   fields_under_root: true
>   {{if .Stdout}}
>   docker-json: true
>   {{end}}
>   {{if eq .Format "json"}}
>   json.keys_under_root: true
>   {{end}}
>   fields:
>       {{range $key, $value := .CustomFields}}
>       {{ $key }}: {{ $value }}
>       {{end}}
>       {{range $key, $value := .Tags}}
>       {{ $key }}: {{ $value }}
>       {{end}}
>       {{range $key, $value := $.container}}
>       {{ $key }}: {{ $value }}
>       {{end}}
>   {{range $key, $value := .CustomConfigs}}
>   {{ $key }}: {{ $value }}
>   {{end}}
>   tail_files: false
>   close_inactive: 2h
>   close_eof: false
>   close_removed: true
>   clean_removed: true
>   close_renamed: false
> 
> {{end}}
> ```
> 
> 错误日志如下：
> ![error-log](https://camo.githubusercontent.com/2191e4653a0d07cda5e03fd9e4f430e8a2a2e72c/68747470733a2f2f747661312e73696e61696d672e636e2f6c617267652f30303753385a496c677931676666347a37796b34366a333238693038347772362e6a7067)

我当年用的是 0.9.6, 你用0.9.7应该是一样的。你的操作步骤是怎样的，是按下面这位同学说的操作的吗？


> 把filebeat.tpl 配置 新增 multiline 即可
> 重新生成一个镜像 tomcat多行日志即可合并
> vim filebeat.tpl
> {{range .configList}}
> ...
> multiline.pattern: '^[[:space:]]+(at|.{3})\b|^Caused by:'
> multiline.negate: false
> multiline.match: after
> multiline.max_lines: 10000
> scan_frequency: 10s

**Comment by currycan** [comment]
@omegazeng 是的，我基于`registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.7-filebeat`版本重做了一个镜像，替换`filebeat.tpl `文件，但是报错了。
正则表达式是参考：https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html#multiline-examples

**Comment by omegazeng** [comment]
> @omegazeng 是的，我基于`registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.7-filebeat`版本重做了一个镜像，替换`filebeat.tpl `文件，但是报错了。
> 正则表达式是参考：https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html#multiline-examples

替换`filebeat.tpl `文件报错了，什么意思？怎么替换的。
这个文件是在重新构建log-pilot镜像时替换的。
下面简单记录了我的操作。

### 首先根据自己业务的日志格式，编写用于匹配多行日志的正则，你参考的[filebeat正则表达式](https://www.elastic.co/guide/en/beats/filebeat/current/multiline-examples.html#multiline-examples)文档是中还有用于测试正则的说明，可以在线测试你的日志内容和正则表达式 https://play.golang.org/p/uAd5XHxscu

### 重新构建log-pilot镜像
以下是我的模板文件和Dockerfile
* filebeat.tpl
```tpl
{{range .configList}}
- type: log
  enabled: true
  paths:
      - {{ .HostDir }}/{{ .File }}
  multiline.pattern: '^\[|\{|([0-9]{4}-[0-9]{2}-[0-9]{2})|([0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3})|([0-9]{1,2}-[A-Za-z]{3}-[0-9]{4})'
  multiline.negate: true
  multiline.match: after
  multiline.max_lines: 10000
  scan_frequency: 10s
  fields_under_root: true
  {{if .Stdout}}
  docker-json: true
  {{end}}
  {{if eq .Format "json"}}
  json.keys_under_root: true
  {{end}}
  fields:
      {{range $key, $value := .Tags}}
      {{ $key }}: {{ $value }}
      {{end}}
      {{range $key, $value := $.container}}
      {{ $key }}: {{ $value }}
      {{end}}
  tail_files: false
  close_inactive: 2h
  close_eof: false
  close_removed: true
  clean_removed: true
  close_renamed: false

{{end}}
```
* Dockerfile
```Dockerfile
FROM registry.cn-hangzhou.aliyuncs.com/acs/log-pilot:0.9.6-filebeat
COPY filebeat.tpl /pilot/
```

DaemonSet，把新构建的log-pilot更新到k8s中

* log-pilot-filebeat.yaml
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: log-pilot
  labels:
    app: log-pilot
  namespace: kube-system
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: log-pilot
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: log-pilot
        image: harbor.example.com/library/log-pilot:0.9.6-multiline-1
        resources:
          limits:
            memory: 1000Mi
          requests:
            cpu: 200m
            memory: 200Mi
        env:
          - name: "NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: "LOGGING_OUTPUT"
            value: "elasticsearch"
          - name: "ELASTICSEARCH_HOSTS"
             value: "172.16.10.166:9200,172.16.10.167:9200,172.16.10.168:9200"
        volumeMounts:
        - name: sock
          mountPath: /var/run/docker.sock
        - name: root
          mountPath: /host
          readOnly: true
        - name: varlib
          mountPath: /var/lib/filebeat
        - name: varlog
          mountPath: /var/log/filebeat
        - name: localtime
          mountPath: /etc/localtime
          readOnly: true
        livenessProbe:
          failureThreshold: 3
          exec:
            command:
            - /pilot/healthz
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 2
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sock
        hostPath:
          path: /var/run/docker.sock
      - name: root
        hostPath:
          path: /
      - name: varlib
        hostPath:
          path: /var/lib/filebeat
          type: DirectoryOrCreate
      - name: varlog
        hostPath:
          path: /var/log/filebeat
          type: DirectoryOrCreate
      - name: localtime
        hostPath:
          path: /etc/localtime
```
最后就可以按官方文档，采集日志了。
