### ISSUE TITLE
有些疑问能否解答一下？

### ISSUE THREAD

**Issue by wajika** [AliyunContainerService/log-pilot#195]
```
log-pilot配置
        env:
          - name: "NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: "LOGGING_OUTPUT"
            value: "redis"
          - name: "REDIS_HOST"
            value: "192.168.1.1"
          - name: "REDIS_PORT"
            value: "6379"
          - name: "REDIS_PASSWORD"
            value: "test"
          - name: "REDIS_DATATYPE"
            value: "list"
容器配置：
spec:
  containers:
  - env:
    - name: aliyun_logs_catalina            #这里标记的catalina是否就是最后输出的index名字？
      value: /applog/logs/*/*.log           #这个目录是否需要用hostpath先挂出来？
    - name: aliyun.logs.catalina.tags     #这个tag可以直接指定一个名字用于tag分类吗？
      value: "env=ceshi"       
volumeMounts:
    - mountPath: /applog/logs
      name: log
    - mountPath: /etc/localtime
      name: config
      readOnly: true
    - mountPath: /usr/local/tomcat/logs
      name: log
  volumes:
  - hostPath:
      path: /applog/logs
      type: ""
    name: log
  - hostPath:
      path: /etc/localtime
      type: ""      

```
第一个问题：aliyun_logs_catalina 这样配置的话按理输出的index叫catalina 对吗？但是我在redis上看到的是filebeat
第二个问题：/applog/logs/*/*.log 这个目录用empty的话，是否靠谱？使用首页提供的默认配置，pod出现异常，重启后好像不会再次输出日志。
第三个问题：aliyun.logs.catalina.tags=“测试环境”    有没有一种方法不往index中加字段的？但是可以区别不同的index
第四个问题：我的链路是这样 k8s(log-pilot) tag---- >  redis ----> logstash ---> es,  加了tag后 ，logstash这里怎么读取到tag标记？
第五个问题：K8S集群中既有nginx部署也有应用服务的部署，我需要给每个pod都加上两个label path吗？
