### ISSUE TITLE
使用ES存储数据，登录容器发现filebeat配置文件输出依旧为console

### ISSUE THREAD

**Issue by EricBatty** [AliyunContainerService/log-pilot#212]
运行命令
```
docker run --rm -it     -v /var/run/docker.sock:/var/run/docker.sock   \
  -v /:/host:ro \
 -v /etc/localtime:/etc/localtime   \
 --privileged \
 -e FLUENTD_OUTPUT=elasticsearch  \
--cap-add SYS_ADMIN  \
-e ELASTICSEARCH_HOST=192.168.0.120  \
-e ELASTICSEARCH_PORT=9500   \
  registry.cn-hangzhou.aliyuncs.com/acs-sample/log-pilot:0.9.5-filebeat
```
查看filebeat配置文件
```
/pilot # cat /etc/filebeat/filebeat.yml 
path.config: /etc/filebeat
path.logs: /var/log/filebeat
path.data: /var/lib/filebeat/data
filebeat.registry_file: /var/lib/filebeat/registry
filebeat.shutdown_timeout: 0
logging.level: info
logging.metrics.enabled: false
logging.files.rotateeverybytes: 104857600
logging.files.keepfiles: 10
logging.files.permissions: 0600

setup.template.name: "filebeat"
setup.template.pattern: "filebeat-*"
filebeat.config:
    prospectors:
        enabled: true
        path: ${path.config}/prospectors.d/*.yml
        reload.enabled: true
        reload.period: 10s

output.console:
    pretty: false
```
查看 config.filebeat 脚本，变量判断
```
case "$LOGGING_OUTPUT" in                                                                                
    elasticsearch)                                                                                       
        es;;                                                                                             
    logstash)                                                                                            
        logstash;;                                                                                       
    file)                                                                                                
        file;;                                                                                           
    redis)                                                                                               
        redis;;                                                                                          
    kafka)                                                                                               
        kafka;;                                                                                          
    count)                                                                                               
        count;;                                                                                          
    *)                                                                                                   
        default                                                                                          
esac 
```
与命令行变量名不一致 FLUENTD_OUTPUT=elasticsearch
