### ISSUE TITLE
pod删除时日志重复采集，以下是我的配置

### ISSUE THREAD

**Issue by JDalready** [AliyunContainerService/log-pilot#267]
每次更新配置重启pod或者删除重启都会采集大量重复日志
版本：0.9.7
采集方式：log-pilot-fluentd
yaml
```yaml
apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: log-pilot
  namespace: elk
  labels:
    k8s-app: log-pilot
spec:
  updateStrategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        k8s-app: log-pilot
      annotations: 
        last-updated: '2019-09-11 22:46:22'
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      containers:
      - name: log-pilot
        image: ***/log-pilot-fluentd:0.9.7
        env:
          - name: "LOGGING_OUTPUT"
            value: "splunk"
          - name: "NODE_NAME"
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
        volumeMounts:
        - mountPath: /pilot/fluentd.tpl
          subPath: fluentd.tpl
          name: config-volume
        - mountPath: /pilot/config.fluentd
          subPath: config.fluentd
          name: config-volume
        - name: sock
          mountPath: /var/run/docker.sock
        - name: root
          mountPath: /host
          readOnly: true
        - name: pos
          mountPath: /pilot/pos
        - name: localtime
          mountPath: /etc/localtime
        securityContext:
          capabilities:
            add:
            - SYS_ADMIN
      terminationGracePeriodSeconds: 30
      volumes:
      - name: sock
        hostPath:
          path: /var/run/docker.sock
      - name: root
        hostPath:
          path: /
      - name: pos
        emptyDir: {}
      - name: localtime
        hostPath:
          path: /etc/localtime
      - name: config-volume
        configMap:
          defaultMode: 0777
          name: log-pilot-conf
```
很想知道什么原因，希望得到回答
