### ISSUE TITLE
log-pilot是否可以支持基于容器的env或者label自定义生成tags

### ISSUE THREAD

**Issue by Colstuwjx** [AliyunContainerService/log-pilot#274]
如题，比如我想把pod分配得到的IP作为elk录入日志记录的一个tag，目前是很难做到的，因为一般是我在启动容器之后才能知道拿到了哪个IP，log-pilot目前这块我看到是写死了一部分 [代码](https://github.com/AliyunContainerService/log-pilot/blob/af6da63aa35e3377c8e44dc951c4ea8ffe7c0bb5/pilot/pilot.go#L324) 。

能否支持像自定义配置那样，自定义把哪些env或者label作为采集到elk日志的tags的一部分？这样的话，比如pod ip我可以通过如下方式映射到env，然后再指定让log-pilot消费该env作为tag：

```
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
```

谢谢！
