### ISSUE TITLE
容器收集时收集额外的信息太多了，能否通过配置的方式减少

### ISSUE THREAD

**Issue by lvhuat** [AliyunContainerService/log-pilot#319]
我明白日志收集是按行收集的，收集后会封装成为一个json格式并且推送给kafka，
但是这意味着，我实际日志无论再小，都会因为封装变得很大
```

{
//....... 额外信息
message:"hello world",
//...... 额外信息
}
```
我发现额外信息竟然达到惊人的1k，其序列化，组装和压缩给日志收集主机的计算造成了挑战，请问有什么办法可以通过配置来定义额外信息的选择性发送么？

**Comment by oscarlear** [comment]
如果是用filebeat收集的，可以修改源码 assets/filebeat/config.filebeat 文件，设置输出格式只有日志内容 ![图片](https://user-images.githubusercontent.com/24838259/105456520-42da2180-5cc0-11eb-9937-dbbc535fc334.png)

**Comment by oscarlear** [comment]
如果是用 filebeat 方式收集，可以修改 assets/filebeat/config.filebeat 文件，设置只输出日志的内容
```
output.kafka:
    hosts: [$KAFKA_BROKERS]
    topic: '%{[topic]}'
    codec.format:
      string: '%{[message]}'
```
