### ISSUE TITLE
请问fluentd-pilot 可以配置健康检查吗

### ISSUE THREAD

**Issue by zzp8164** [AliyunContainerService/log-pilot#49]
此前遇到过一个问题，fluentd 服务假死，但是该容器还存活，并不能收集日志。

期望通过配置health check 来解决该问题，请问有配置的方式吗？ 

谢谢🙏

**Comment by mengskysama** [comment]
我这边可以重现的一个类似的问题是，有一个写日志洪峰导致oom，fluentd主进程被干趴了，但是pilot还活着的情况，我打算给pilot加个守护看看。

**Comment by mengskysama** [comment]
Mem: 3365088K used, 516604K free, 1884K shrd, 61000K buff, 1674788K cached
CPU:  27% usr   9% sys   0% nic  51% idle   0% io   0% irq  11% sirq
Load average: 2.24 3.54 4.25 3/502 32460
  PID  PPID USER     STAT   VSZ %VSZ CPU %CPU COMMAND
    5     1 root     S    13448   0%   1   0% /pilot/pilot -template /pilot/fluentd.tpl -base /host -log-level debug
32455     0 root     S     1532   0%   0   0% sh
32460 32455 root     R     1524   0%   1   0% top
    1     0 root     S     1520   0%   1   0% /bin/sh -c /pilot/entrypoint
   24     5 root     Z        0   0%   0   0% [fluentd]

今天发现僵尸进程的情况，用稳定的2000条/秒压了半天，3个worker其中1个worker的除了问题

**Comment by suyuan1203** [comment]
配置了一个简单的health check, 暂时解决了问题。以后有空看看能不能利用fluentd的API做health check
```
livenessProbe:
    exec:
        command:
        - /bin/sh
        - -c
        - if [ $(ps | grep '/usr/bin/ruby' | wc -l) -eq 1 ];then exit 1;else exit 0; fi
    initialDelaySeconds: 5
    periodSeconds: 5
```
用这个工具以来，碰到过好几次坑，😓
